### ISSUE TITLE
How to indent with two spaces only?

### ISSUE THREAD

**Issue by M-Reimer** [emacs-php/php-mode#398] opened 2018-01-10 15:35 UTC
I've tried several things, so far, but without success.

So far I have:

(setq js-indent-level 2)
(setq-default c-basic-offset 2)
(setq c-basic-offset 2)
(setq-default tab-width 2)
(setq-default c-basic-indent 2)

I also have "indent-tabs-mode nil".

What do I have to do that I always get two spaces for indentation? Please provide a few lines that just work when placed in my .emacs. Thanks in advance.

**Comment by MarTango** [comment] 2018-01-10 16:02
`(setq c-basic-offset 2)` works for me

**Comment by MarTango** [comment] 2018-01-10 16:05
Maybe something like
`(add-hook 'php-mode-hook #'(lambda() (setq c-basic-offset 2)))` ?

**Comment by zonuexe** [comment] 2018-01-14 17:40
@M-Reimer 
In general, what @MarTango says is the right solution.
If your .emacs (`init.el`) file becomes public, we may be able to point out mistakes.

**Comment by M-Reimer** [comment] 2018-02-13 16:42
Sorry for the late response. My .emacs:

`
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(show-trailing-whitespace t)
 '(tab-width 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )



(setq js-indent-level 2)
(setq-default c-basic-offset 2)
(setq c-basic-offset 2)
(setq-default tab-width 2)
(setq-default c-basic-indent 2)

(autoload 'php-mode "php-mode.el" "Php mode." t)
(add-to-list 'auto-mode-alist '("\\.php[345]?$" . php-mode))

(add-hook 'php-mode-hook #'(lambda() (setq c-basic-offset 2)))
`

**Comment by zonuexe** [comment] 2018-02-13 18:34
@M-Reimer 
Is this part of your .emacs?  There is no mistake in this setting, but the information is missing.

Can you provide additional debugging information?

Paste the following code in `*scratch*` buffer, evaluate it, and run `M-x php-mode-debug` in the buffer of any PHP file.

```el
(defun php-mode-debug ()
  "Display informations useful for debugging PHP Mode."
  (interactive)
  (message "--- PHP-MODE DEBUG BEGIN ---")
  (message "versions: %s; %s" (emacs-version) (php-mode-version))
  (message "major-mode: %s" major-mode)
  (message "minor-modes: %s" (cl-remove-if
                              (lambda (s) (string-match-p "global" (symbol-name s)))
                              minor-mode-list))
  (message "variables: %s"
           (cl-loop for v in '(indent-tabs-mode tab-width)
                    collect (list v (symbol-value v))))
  (message "custom variables: %s"
           (cl-loop for (v type) in (custom-group-members 'php nil)
                    if (eq type 'custom-variable)
                    collect (list v (symbol-value v))))
  (message "c-indentation-style: %s" c-indentation-style)
  (message "c-style-variables: %s" (c-get-style-variables c-indentation-style nil))
  (message "--- PHP-MODE DEBUG END ---")
  (switch-to-buffer "*Messages*")
  (goto-char (point-max)))
```

**Comment by forthrin** [comment] 2018-03-12 19:00
I have the same problem. Indent was 2 using a mid-2017 version of php-mode. Updated to latest version and indent changed to 4. How do I set indent to 2 for all .php files?

Version:

```
PHP Mode 1.19.0 of 2018-03-05
versions: GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0)
 of 2017-09-12; PHP Mode 1.19.0 of 2018-03-05
```

.emacs:

```
(add-hook 'php-mode-hook '(lambda ()
                            (setq c-basic-offset 2)))
```

Variable (while in a .php file):

```
c-basic-offset is a variable defined in ‘cc-vars.el’.
Its value is 4
Original value was set-from-style
Local in buffer a.php; global value is 2
```

Workaround (while in a .php file):

    M-x set-variable RET c-basic-offset RET 2

**Comment by zonuexe** [comment] 2018-03-13 03:44
@forthrin Thanks for reporting.
By this report I clearly understood the cause.  We will release the modified version in a few days.

**Comment by forthrin** [comment] 2018-03-24 11:58
@zonuexe: Using 20180323.512, `c-basic-offset` is still 4 for PHP buffers, even though my `.emacs` sets it to two (see previous post). Could you have a look at this again?

**Comment by zonuexe** [comment] 2018-03-24 12:11
@forthrin I am sorry, I was aware of this problem. This was partially resolved in #442, but it does not apply to cases reported from you. I have an idea to fix this, so I can start right away.

**Comment by zonuexe** [comment] 2018-03-25 08:03
@forthrin Hi, I think this problem was solved in `master` branch by the MR above.
(It was released as [`20180324.656` at MELPA](https://melpa.org/#/php-mode))

**Comment by forthrin** [comment] 2018-03-25 17:14
WFM

**Comment by jidaikobo-shibata** [comment] 2018-03-26 12:59
Hi,

I'm using php-mode-20180325.112.

But my indent became 4. By using below, indent will be 2. But I have to do this action when open each php files :-(

M-x php-mode

My init.el is here
https://github.com/jidaikobo-shibata/dotemacs/blob/master/jidaikobo.init.el

Please give me a clew m(._.)m

**Comment by zonuexe** [comment] 2018-03-26 13:04
@jidaikobo-shibata Thank you for reporting.
Can you tell me your version of Emacs?

**Comment by jidaikobo-shibata** [comment] 2018-03-27 01:04
@zonuexe thank you for replying. I'm using 25.3.

**Comment by oschonrock** [comment] 2019-01-15 15:01
Since upgrading from php-mode 18.4 => 21.0 I also have a problem with c-basic-offset. It's always 4. 

**Background**

my .emacs (actually default.el, cut down to just what matters)

```elisp
(autoload 'php-mode "php-mode" "Mode for editing PHP source files")
(add-to-list 'auto-mode-alist '("\\.\\(inc\\|php[s34]?\\)" . php-mode))
```
my php-mode-debug output is:
```elisp
--- PHP-MODE DEBUG BEGIN ---
versions: GNU Emacs 26.1 (build 1, amd64-portbld-freebsd11.2); PHP Mode 1.21.0 of 2019-01-09
package-version: nil
major-mode: php-mode
minor-modes: (show-paren-mode tooltip-mode electric-indent-mode file-name-shadow-mode font-lock-mode auto-composition-mode auto-encryption-mode auto-compression-mode line-number-mode transient-mark-mode abbrev-mode)
variables: ((indent-tabs-mode nil) (tab-width 2))
custom variables: ((php-search-documentation-browser-function nil) (php-class-suffix-when-insert ::) (php-namespace-suffix-when-insert \))
c-indentation-style: drupal
c-style-variables: ((c-basic-offset 4) (c-comment-only-line-offset 0) (c-indent-comment-alist ((anchored-comment column . 0) (end-block space . 1) (cpp-end-block space . 2))) (c-indent-comments-syntactically-p nil) (c-block-comment-prefix * ) (c-comment-prefix-regexp ((pike-mode . //+!?\|\**) (awk-mode . #+) (other . //+\|\**))) (c-cleanup-list (scope-operator)) (c-hanging-braces-alist ((brace-list-open) (brace-entry-open) (statement-cont) (substatement-open after) (block-close . c-snug-do-while) (extern-lang-open after) (namespace-open after) (module-open after) (composition-open after) (inexpr-class-open after) (inexpr-class-close before) (arglist-cont-nonempty))) (c-hanging-colons-alist nil) (c-hanging-semi&comma-criteria (c-semi&comma-inside-parenlist)) (c-backslash-column 48) (c-backslash-max-column 72) (c-special-indent-hook nil) (c-label-minimum-indentation 1))
c-doc-comment-style: ((java-mode . javadoc) (pike-mode . autodoc) (c-mode . gtkdoc))
c-offsets-alist: ((inexpr-class . +) (inexpr-statement . +) (lambda-intro-cont . +) (inlambda . 0) (template-args-cont c-lineup-template-args +) (incomposition . +) (inmodule . +) (innamespace . +) (inextern-lang . +) (composition-close . 0) (module-close . 0) (namespace-close . 0) (extern-lang-close . 0) (composition-open . 0) (module-open . 0) (namespace-open . 0) (extern-lang-open . 0) (objc-method-call-cont c-lineup-ObjC-method-call-colons c-lineup-ObjC-method-call +) (objc-method-args-cont . c-lineup-ObjC-method-args) (objc-method-intro . [0]) (friend . 0) (cpp-define-intro c-lineup-cpp-define +) (cpp-macro-cont . +) (cpp-macro . [0]) (inclass . +) (stream-op . c-lineup-streamop) (arglist-cont-nonempty first php-lineup-cascaded-calls c-lineup-arglist) (arglist-cont first php-lineup-cascaded-calls 0) (comment-intro . 0) (catch-clause . 0) (else-clause . 0) (do-while-closure . 0) (access-label . -) (case-label . +) (substatement . +) (statement-case-intro . +) (statement . 0) (brace-entry-open . 0) (brace-list-entry . c-lineup-under-anchor) (brace-list-close . 0) (block-close . 0) (block-open . 0) (inher-cont . c-lineup-multi-inher) (inher-intro . +) (member-init-cont . c-lineup-multi-inher) (member-init-intro . +) (annotation-var-cont . +) (annotation-top-cont . 0) (topmost-intro . 0) (knr-argdecl . 0) (func-decl-cont . +) (inline-close . 0) (class-close . 0) (class-open . 0) (defun-block-intro . +) (defun-close . 0) (defun-open . 0) (c . c-lineup-C-comments) (string . c-lineup-dont-change) (topmost-intro-cont first php-lineup-cascaded-calls +) (brace-list-intro . +) (brace-list-open . 0) (inline-open . 0) (arglist-close . php-lineup-arglist-close) (arglist-intro . php-lineup-arglist-intro) (statement-cont first php-lineup-cascaded-calls php-lineup-string-cont +) (statement-case-open . 0) (label . +) (substatement-label . 2) (substatement-open . 0) (knr-argdecl-intro . +) (statement-block-intro . +))
--- PHP-MODE DEBUG END ---
```
When opening a new php file with emacs
```bash
$ emacs test.php
```
```php
<?php

if (true) {
    // tab goes here
}
```

and c-basic-offset = 4
```
M-x describe-variable c-basic-offset
c-basic-offset is a variable defined in ‘cc-vars.el’.
Its value is 4
Original value was set-from-style
Local in buffer test.php; global value is set-from-style
```

This is pear-coding style which should be 4. So far so good. If I then change to drupal style which should have a c-basic-offset=2
```
M-x php-set-style drupal
```
The behaviour is no different, ie c-basic-offset=4 (and describe-variable still reports that), even though I can tell that drupal style is active, because whitespace at end of line starts being highlighted. 

if I manually set c-basic-offset=2:
```
M-x  set-variable c-basic-offset 2
```
It works!

I have tried setting the following in .emacs:
```elisp
(setq php-mode-disable-c-mode-hook nil)
(setq-default php-mode-enable-project-coding-style nil)
```
But this makes no difference to the above described behaviour. 

I have also tried enabling drupal mode via the hook:
```elisp
(add-hook 'php-mode-hook 'php-enable-drupal-coding-style)
```
No different, same as enabling it via `M-x php-set-style drupal`. The mode is active (end of line whitespace highlighting in on), but c-basic-offset still behaves like =4 and emacs reports it as 4. 

I also tried setting the style in .emacs via a lamba:
```elisp
(add-hook 'php-mode-hook #'(lambda() (php-enable-drupal-coding-style)))
```
Same again. Drupal mode is active, but c-basic-offset = 4. 

The workaround metioned here:
https://github.com/junkw/dot.emacs.d/commit/879ee5f62ce0e53afd952a65b2dd668a6ee96522

DOES WORK!

.emacs
```elisp
(add-hook 'php-mode-hook #'(lambda()
                             (php-enable-drupal-coding-style)
                             (setq c-basic-offset 2)))
```
Drupal mode active, and c-basic-offset = 2!

So basically the built in coding styles were broken at some point between 18.4 and 21.0 (or change in emacs or cc-mode, see below). Seems like some kind of timing/delay issue about when c-basic-offset is set? 

**Is a change in cc-mode responsible ? Unlikely?**
Refer this footnote here 
https://www.gnu.org/software/emacs/manual/html_node/ccmode/Style-Variables.html#fnd-1

cc-mode 5.26 is ancient:
http://cc-mode.sourceforge.net/src/ChangeLog
```
Sun Nov 21 1999  Martin Stjernholm  <bug-cc-mode@gnu.org>
	* Release 5.26
```

The most recent change in cc-mode is from 2016, so this seems unlikely Is there a more recent change

(Note I am actually trying to create my own coding style, by copying/modifying one of the others. This has the same problems. But all of the above was done with the unmodified php-mode.el)

**Comment by serv-inc** [comment] 2019-07-03 04:11
@zonuexe : your politeness is refreshing, domo arigato gozaimashu!

**Closed** 2019-07-03 05:10 UTC
Labels: Question
