### ISSUE TITLE
Ident breaks for files starting with a shebang

### ISSUE THREAD

**Issue by etu** [emacs-php/php-mode#27] opened 2012-11-22 19:01 UTC
Yeah, I do scripting in PHP sometimes, and want to run them as executables like any other file.

The common way to do this is:

``` php
#!/usr/bin/env php
<?php
if(1 == 1) {
<tab>
```

Results in no indent.

**Comment by forthrin** [comment] 2018-03-26 17:38
@ejmr: I regret to report this DOES still happen, in the worst possible way: Irreproducible. Retelling:

1. Start with some code (1st example)
2. Add braces around `echo`
3. Press tab on `echo` line
4. Incorrect indentation! (2nd example) -- but only when the tide is high in India
5. Remove shebang line
6. Repeat 3
7.  Correct indentation!
8. Add shebang line
9. Save, kill and re-open file
10. Repeat 3
11. Correct indentation! WTF!?

Can the fact the error goes away when you reopen the buffer help fix this pesky varmint?

```
#!/usr/bin/env php
<?php

$file = file_get_contents("file.txt");
$chunks = str_split($file, 256);
foreach($chunks as $chunk)
  echo base64_encode($chunk) . "\n";

?>
```

```
#!/usr/bin/env php
<?php

$file = file_get_contents("file.txt");
$chunks = str_split($file, 256);
foreach($chunks as $chunk) {
echo base64_encode($chunk) . "\n";
}

?>
```

**Comment by ejmr** [comment] 2018-03-27 08:05
@forthrin I no longer maintain or work on PHP Mode, and nowadays usually do not respond to notifications about it, but I want to make sure @zonuexe is aware of this issue.  He is the current maintainer, and more importantly he will do a much better job than me at figuring out a solution to this issue.

For what it's worth, I tried to duplicate the error again, yet again I could not.  Some important info from the output of `php-mode-debug`:

```
--- PHP-MODE DEBUG BEGIN ---
PHP Mode 1.19.0 of 2018-03-26
versions: GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit)
 of 2018-03-25; PHP Mode 1.19.0 of 2018-03-26
major-mode: php-mode
minor-modes: (ivy-mode tooltip-mode electric-indent-mode mouse-wheel-mode file-name-shadow-mode font-lock-mode auto-composition-mode auto-encryption-mode auto-compression-mode line-number-mode transient-mark-mode abbrev-mode)

[...]
```

@zonuexe Please let me know if any other info would help you in debugging this.

As an aside, maybe it would be a good idea to re-open this issue and also create a tag like *"Cannot Reproduce"* or something similar, something to indicate that there is a bug but it is not one everyone can reliably duplicate.

**Comment by forthrin** [comment] 2018-03-27 14:06
@emjr: @zonuexe: I don't have permission to reopen or tag the issue, but I'll help with any testing necessary. My guess is the bug doesn't depend on other `.emacs` settings. Mine is pretty simple.

**Comment by zonuexe** [comment] 2018-03-27 14:31
@forthrin @ejmr Thanks for suggestion.
I would like to address this issue under the testimony of @forthrin.
This problem was marked as one of the issues to be addressed for the next stable release to be released.

-----

(By the way, because I am not the owner of this repository, I can not receive notification of all issues from GitHub's features and mails. But since I use [NotHub](http://nothub.org/), if I am luckily in front of the computer I can detect all notifications at the same time. )

**Comment by zonuexe** [comment] 2019-05-11 22:14
I'm closing it because it looks like there is no problem today.

**Closed by zonuexe** 2019-05-11 22:14 UTC
Labels: Bug
