### ISSUE TITLE
Chained method calls aren't indented

### ISSUE THREAD

**Issue by metaturso** [emacs-php/php-mode#19] opened 2012-09-06 06:46 UTC
Chained method calls are not aligned to the first object operator in php-mode 1.6.6 and Emacs 24.2.

Indenting a region such as 

```
    $object = new SomeClass();
    $object->method()
           ->another();
```

produces the same result as previous version of php-mode

```
    $object = new SomeClass();
    $object->method()
    ->another();
```

**Comment by fabacino** [comment] 2019-03-04 16:10
Is this still a problem? I cannot reproduce with v1.21

**Comment by zonuexe** [comment] 2019-05-11 22:12
I'm closing it because it looks like there is no problem today.

**Closed by zonuexe** 2019-05-11 22:12 UTC
